---
- name: 添加 Neovim PPA
  shell: add-apt-repository ppa:neovim-ppa/unstable -y
  tags:
    - neovim
    - editor
    - nvim
    - vim
    - vi

- name: 安装 Neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
  tags:
    - neovim
    - editor
    - nvim
    - vim
    - vi
