---
- name: 安装 Coreutils
  homebrew:
    name: coreutils
    state: present
    update_homebrew: yes
  tags:
    - fish
    - shell

- name: 配置 coreutils 环境
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/conf.d/01-coreutils.fish"
    block: |
      #------------------------------
      # GNU Tools
      #------------------------------
      if test -d "$(brew --prefix coreutils)" >/dev/null 2>&1
        export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
      end
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    mode: '0600'
  tags:
    - fish
    - shell
