---
- name: 添加 Fish Shell PPA
  shell: apt-add-repository ppa:fish-shell/release-4 -y
  tags:
    - fish
    - shell

- name: 安装 Fish Shell
  apt:
    name: fish
    state: present
    update_cache: yes
  tags:
    - fish
    - shell
