---
galaxy_info:
  role_name: nodejs
  author: keveon
  description: Node.js 运行时安装和配置
  company:
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: CentOS
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - node
    - nodejs
    - javascript
    - typescript
    - programming
    - development

dependencies: [ ]