---
galaxy_info:
  role_name: docker
  author: keveon
  description: 安装和配置 Docker 环境
  company: keveon
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: CentOS
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - docker
    - container
    - devops
    - development 

dependencies: [] 